<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Plan</name>
   <tag></tag>
   <elementGuidId>a85991f4-02fd-4fbc-83b5-5e3f341a3600</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div[2]/a[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>683b9122-1365-4beb-8fac-8b26c066f035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Plan retirement</value>
      <webElementGuid>c90c4863-1815-4af1-b4e4-66c38fce5e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StepLink__StyledLink-sc-1iedwva-0 eZWMlC</value>
      <webElementGuid>1a2da758-7771-4bcd-b56b-6ec631907e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/planning/plan/913bae97eaf8fba686f0d844e6eb7189</value>
      <webElementGuid>ee75839c-945d-451f-8e36-901836807d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Plan</value>
      <webElementGuid>046aec93-5526-4333-a915-6077e98d82c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[2]/div[@class=&quot;Navigation__LeftNav-sc-ki3bt8-0 degmbO&quot;]/a[@class=&quot;StepLink__StyledLink-sc-1iedwva-0 eZWMlC&quot;]</value>
      <webElementGuid>5c6ec900-0c19-4b78-9237-41abb870668e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]/a[5]</value>
      <webElementGuid>d9915ee7-6194-46d4-8ac7-c1b41e8f6f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Risk'])[1]/following::a[1]</value>
      <webElementGuid>dc42813e-5482-413d-a60e-4fa95fee8d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expenses'])[1]/following::a[2]</value>
      <webElementGuid>ab2a02b1-20e3-4ac6-8ec9-6f307d10729d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compare'])[1]/preceding::a[1]</value>
      <webElementGuid>80e6f626-13a3-4024-9a3b-ed33294f8e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/planning/plan/913bae97eaf8fba686f0d844e6eb7189')]</value>
      <webElementGuid>97e18e27-a979-43fa-a6da-061bc459f9b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>4373803c-3cf5-47ab-8ba0-01cd252d9b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Plan retirement' and @href = '/planning/plan/913bae97eaf8fba686f0d844e6eb7189' and (text() = 'Plan' or . = 'Plan')]</value>
      <webElementGuid>4724cf0a-b39d-4e61-a7e2-65e8cd5220b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
