<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Employer_AssetsList__EditButton-sc-n_517339</name>
   <tag></tag>
   <elementGuidId>7787cba9-4766-4b2c-985b-2bf99a250e22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.AssetsList__EditButton-sc-nh3q7p-2.fWAPFA.btn-secondary.btn.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b909a350-0bdf-4841-a601-a2887f81eec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>0baca165-a7c6-4dc7-96b8-1556af10868a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>00af1183-6e02-499c-a2bd-054411ab46a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AssetsList__EditButton-sc-nh3q7p-2 fWAPFA btn-secondary btn btn-primary</value>
      <webElementGuid>46bc5fec-0a74-42e9-8645-1a7403e56e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assets-tabpane-assets&quot;)/table[@class=&quot;table&quot;]/tbody[1]/tr[1]/td[8]/div[@class=&quot;AssetsList__RightButtons-sc-nh3q7p-1 gzNxXO&quot;]/button[@class=&quot;AssetsList__EditButton-sc-nh3q7p-2 fWAPFA btn-secondary btn btn-primary&quot;]</value>
      <webElementGuid>aa6e7c1a-b653-484b-bb50-154d9ee6d7fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>10bb5d1b-7b54-48c5-855a-ad5aff23d760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='assets-tabpane-assets']/table/tbody/tr/td[8]/div/button</value>
      <webElementGuid>92130ee8-3a07-4d0f-9492-7e859b2ada43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employer:'])[1]/following::button[1]</value>
      <webElementGuid>1ce7aeff-be16-4ed8-9d14-9857652a6214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$24,000/yr'])[1]/following::button[1]</value>
      <webElementGuid>464b4fb4-122f-4486-a230-4a62bec405d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$2,000,000'])[2]/preceding::button[2]</value>
      <webElementGuid>22c5b0a3-1b91-4e49-9cc2-4b30d487b707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADD ASSET'])[1]/preceding::button[2]</value>
      <webElementGuid>1b4c7dde-6f9c-441f-a0d3-ef1f31587764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/button</value>
      <webElementGuid>53ad16e5-fc00-4d6f-afe0-7e8a4c735838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Edit' and @type = 'button']</value>
      <webElementGuid>b75f47d8-8013-4f67-b822-613ed54c5f8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
