<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Annual_contributionAmountEmployeeCurrency</name>
   <tag></tag>
   <elementGuidId>fadb6f94-2b12-40d8-a7ac-26ff777ea120</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='contributionAmountEmployeeCurrency']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;contributionAmountEmployeeCurrency&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e879d70-8cae-4a81-b343-3d0fb9f0ee93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e305dd72-8032-461e-aeb5-4126c46b29b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contributionAmountEmployeeCurrency</value>
      <webElementGuid>10dc30fa-9e51-4027-a7a5-7c473bf5f615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\$?[0-9]*,?[0-9]*\.?[0-9]*%?</value>
      <webElementGuid>b96a8330-a7b3-4712-a2dd-07df251cb552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f35269a3-395f-4c46-902f-4b4b982c38fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>$1,800</value>
      <webElementGuid>460b888e-ac1f-4b36-a805-144a1c4ab71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>4b8521e7-8ec4-457e-93e7-4725673fea72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ru-y-body-scrollbar modal-open&quot;]/div[@class=&quot;fade StyledModal-sc-91ps9d-0 fALiTF modal show&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/form[1]/div[1]/div[8]/div[5]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;collapse show&quot;]/div[1]/div[@class=&quot;NumberField__Wrapper-sc-1rl9wva-0 kVngqT&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>acd7e9de-d313-4ba5-a7a7-7a79f0f4d21a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='contributionAmountEmployeeCurrency']</value>
      <webElementGuid>7bc10da5-6237-4e34-962f-a4abf3694211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>f724f9e3-95ac-4abd-99f4-35ee5cf09bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'contributionAmountEmployeeCurrency' and @type = 'text']</value>
      <webElementGuid>ec93f43b-b907-490f-9ba1-4d6bc768e942</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
