<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>afe41f07-345a-4b33-821c-e4c4fe943070</testSuiteGuid>
   <testCaseLink>
      <guid>c1d4d11a-8efe-4fce-82be-0f2fb0184041</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FreedomBooking/DDT-freedomBookingSigin</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfa45024-ae97-4af3-a7e4-25756eaad24a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2b9ad71-e537-46e7-86c3-dcc3733adf1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6166d105-3eed-4af3-a0e7-116acb30269d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f70591e4-fc9c-4807-8f2c-349d5cddccd4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36fd9f77-9220-4156-9532-61b09bb00637</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>035beec3-6e94-4da6-aa4b-349472bbdb27</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>dfa45024-ae97-4af3-a7e4-25756eaad24a</id>
         <masked>false</masked>
         <name>baseurl</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/FreedomBooking/DDT-freedomBookingSigin</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>35d8ee0e-1046-4f64-859a-18f908a0ecec</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/New Test Data (2)</testDataId>
      </testDataLink>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7f4b6db7-40e5-42c5-bdcd-f7c8b4b5b8e5</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/New Test Data (3)</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>35d8ee0e-1046-4f64-859a-18f908a0ecec</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>baseurl</value>
         <variableId>dfa45024-ae97-4af3-a7e4-25756eaad24a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>35d8ee0e-1046-4f64-859a-18f908a0ecec</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>c2b9ad71-e537-46e7-86c3-dcc3733adf1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>35d8ee0e-1046-4f64-859a-18f908a0ecec</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>6166d105-3eed-4af3-a0e7-116acb30269d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7f4b6db7-40e5-42c5-bdcd-f7c8b4b5b8e5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>iemail</value>
         <variableId>f70591e4-fc9c-4807-8f2c-349d5cddccd4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7f4b6db7-40e5-42c5-bdcd-f7c8b4b5b8e5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ipassword</value>
         <variableId>36fd9f77-9220-4156-9532-61b09bb00637</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
