<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Continue</name>
   <tag></tag>
   <elementGuidId>6007d2a7-e703-4b55-a1ac-5408b8086b19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.NextButton__NextLink-sc-3gxxhj-0.FQLUQ.btn.btn-sm.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div[3]/div/div/form/div[4]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>44713a5f-af87-4571-903d-cef82c50f268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Continue to next step</value>
      <webElementGuid>dbd154fe-c046-4118-bca8-f6eb491d2bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>NextButton__NextLink-sc-3gxxhj-0 FQLUQ btn btn-sm btn-primary</value>
      <webElementGuid>d0ed67e1-a5fc-4468-bca7-a0882868923c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/planning/sources/913bae97eaf8fba686f0d844e6eb7189</value>
      <webElementGuid>0f291153-6bf7-4af7-abf5-bc4c30e2fb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>deeeddf8-317f-40d3-bd7f-d69a99445375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[2]/div[@class=&quot;Body__Root-sc-jff9vc-0 BegZu&quot;]/div[@class=&quot;Body__Container-sc-jff9vc-1 dVTuVJ&quot;]/div[@class=&quot;InfoContent__Wrapper-sc-6smxw-0 cpEFfe&quot;]/form[1]/div[@class=&quot;footer&quot;]/div[1]/a[@class=&quot;NextButton__NextLink-sc-3gxxhj-0 FQLUQ btn btn-sm btn-primary&quot;]</value>
      <webElementGuid>c3891315-187e-4e95-89bc-58ee795fc176</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[3]/div/div/form/div[4]/div/a</value>
      <webElementGuid>8214c6ba-95cf-42e3-a893-03157dd6b2c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Continue')]</value>
      <webElementGuid>e8dbd8fc-0979-4fd1-92ff-9f20b7756bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shows income split into protected, non-protected, annuity, and shortfalls categories'])[1]/following::a[1]</value>
      <webElementGuid>574e0957-2ffd-401a-997b-9a0d928183ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shows high level summary of yearly income and shortfalls'])[1]/following::a[1]</value>
      <webElementGuid>e3b30b32-28a6-4aab-9b0c-70eda263bd57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Load Max and Ruby'])[1]/preceding::a[1]</value>
      <webElementGuid>81ca3189-349b-4152-8684-88430131c656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need help?'])[1]/preceding::a[1]</value>
      <webElementGuid>d9be392a-d43f-4805-9582-4ef0472345db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>b89185e0-5503-4f23-83ad-d4b357754c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/planning/sources/913bae97eaf8fba686f0d844e6eb7189')])[2]</value>
      <webElementGuid>41052547-a386-4901-8d22-55cc745cff5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a</value>
      <webElementGuid>078218e4-3d22-4326-98d1-c7b805a0aabf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Continue to next step' and @href = '/planning/sources/913bae97eaf8fba686f0d844e6eb7189' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>f5d28842-d9fd-4ae8-861c-1b092d715e95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
