<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_EEndAge</name>
   <tag></tag>
   <elementGuidId>b0187bf7-c1bd-46dc-a77c-0c5a0ddd03cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div[3]/div/div/form/div/div/div/div[2]/div/section[3]/div/div/div/div/div[2]/div[5]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.RetirementRange__StyledHandle-sc-osb66-0.fJEloW.dragging</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;app&quot;)/div[2]/div[@class=&quot;Body__Root-sc-jff9vc-0 BegZu&quot;]/div[@class=&quot;Body__Container-sc-jff9vc-1 dVTuVJ&quot;]/div[@class=&quot;InfoContent__Wrapper-sc-6smxw-0 cpEFfe&quot;]/form[1]/div[@class=&quot;mb-0 form-group row&quot;]/div[@class=&quot;pr-2 col&quot;]/div[@class=&quot;InfoContent__LeftPanel-sc-6smxw-1 hucjNN card&quot;]/div[@class=&quot;card-body&quot;]/div[1]/section[3]/div[@class=&quot;LayoutHelpers__InfoFieldGroup-sc-7ke78-5 bvUyZh&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;px-5 row&quot;]/div[@class=&quot;px-5 col&quot;]/div[@class=&quot;rc-slider rc-slider-with-marks RetirementRange__StyledRange-sc-osb66-1 jMEzFH is-tight&quot;]/div[@class=&quot;rc-slider-handle rc-slider-handle-2 rc-slider-handle-dragging rc-slider-handle-click-focused&quot;]/div[@class=&quot;RetirementRange__StyledHandle-sc-osb66-0 fJEloW dragging&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b92893cf-4dba-4b61-9879-ced4cc1462fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>RetirementRange__StyledHandle-sc-osb66-0 fJEloW dragging</value>
      <webElementGuid>8d6ac3fe-8f75-45c1-a727-69d6c3e36eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EEndAge 72 (2033)</value>
      <webElementGuid>19b4a157-9ca6-4059-abce-ba29cb08cf72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[2]/div[@class=&quot;Body__Root-sc-jff9vc-0 BegZu&quot;]/div[@class=&quot;Body__Container-sc-jff9vc-1 dVTuVJ&quot;]/div[@class=&quot;InfoContent__Wrapper-sc-6smxw-0 cpEFfe&quot;]/form[1]/div[@class=&quot;mb-0 form-group row&quot;]/div[@class=&quot;pr-2 col&quot;]/div[@class=&quot;InfoContent__LeftPanel-sc-6smxw-1 hucjNN card&quot;]/div[@class=&quot;card-body&quot;]/div[1]/section[3]/div[@class=&quot;LayoutHelpers__InfoFieldGroup-sc-7ke78-5 bvUyZh&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;px-5 row&quot;]/div[@class=&quot;px-5 col&quot;]/div[@class=&quot;rc-slider rc-slider-with-marks RetirementRange__StyledRange-sc-osb66-1 jMEzFH is-tight&quot;]/div[@class=&quot;rc-slider-handle rc-slider-handle-2 rc-slider-handle-dragging rc-slider-handle-click-focused&quot;]/div[@class=&quot;RetirementRange__StyledHandle-sc-osb66-0 fJEloW dragging&quot;]</value>
      <webElementGuid>d1423d95-19c0-45a0-9d30-1df4dc970ead</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[3]/div/div/form/div/div/div/div[2]/div/section[3]/div/div/div/div/div[2]/div[5]/div</value>
      <webElementGuid>d026d2cb-ddc8-4a3a-80fd-18c022aa42cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R'])[1]/following::div[3]</value>
      <webElementGuid>e21e5808-33e0-4b4f-b732-f0c6f856e95b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div</value>
      <webElementGuid>7fa08fe5-290a-4aa3-a098-5a7b3f8995cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'EEndAge 72 (2033)' or . = 'EEndAge 72 (2033)')]</value>
      <webElementGuid>eaacef59-0f28-44c8-9962-c8aa068a82c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
