<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_StartAge</name>
   <tag></tag>
   <elementGuidId>80864ddf-3f0e-4917-9d08-298d97d74f99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[2]/div[3]/div[1]/div/form/div[1]/div[1]/div/div[2]/div/section[3]/div/div/div/div/div[1]/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.text-right.col-3 > input[type=&quot;text&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;app&quot;)/div[2]/div[@class=&quot;Body__Root-sc-jff9vc-0 BegZu&quot;]/div[@class=&quot;Body__Container-sc-jff9vc-1 dVTuVJ&quot;]/div[@class=&quot;InfoContent__Wrapper-sc-6smxw-0 cpEFfe&quot;]/form[1]/div[@class=&quot;mb-0 form-group row&quot;]/div[@class=&quot;pr-2 col&quot;]/div[@class=&quot;InfoContent__LeftPanel-sc-6smxw-1 hucjNN card&quot;]/div[@class=&quot;card-body&quot;]/div[1]/section[3]/div[@class=&quot;LayoutHelpers__InfoFieldGroup-sc-7ke78-5 bvUyZh&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;px-5 row&quot;]/div[@class=&quot;px-5 col&quot;]/div[@class=&quot;text-nowrap row&quot;]/div[@class=&quot;text-right col-3&quot;]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>963b9000-9385-4f95-aea4-a816a20d608e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>precision</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4ed04e87-3b5b-4653-bb9b-d7fee542c894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>723adb8c-32fb-4c74-8fc1-5015e29654af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>f3b7a3d6-b652-4357-93d5-f2c3d0801d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>113</value>
      <webElementGuid>d61e07ce-30bd-4c9d-9f55-ed984714b984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a299ad0-e523-424c-9eff-6b00c7556df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>113</value>
      <webElementGuid>91d95676-c09a-4e39-b9e2-8e58dbfa0c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>8d65cb61-6970-4474-ac51-37b7ad56e994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[2]/div[@class=&quot;Body__Root-sc-jff9vc-0 BegZu&quot;]/div[@class=&quot;Body__Container-sc-jff9vc-1 dVTuVJ&quot;]/div[@class=&quot;InfoContent__Wrapper-sc-6smxw-0 cpEFfe&quot;]/form[1]/div[@class=&quot;mb-0 form-group row&quot;]/div[@class=&quot;pr-2 col&quot;]/div[@class=&quot;InfoContent__LeftPanel-sc-6smxw-1 hucjNN card&quot;]/div[@class=&quot;card-body&quot;]/div[1]/section[3]/div[@class=&quot;LayoutHelpers__InfoFieldGroup-sc-7ke78-5 bvUyZh&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;px-5 row&quot;]/div[@class=&quot;px-5 col&quot;]/div[@class=&quot;text-nowrap row&quot;]/div[@class=&quot;text-right col-3&quot;]/input[1]</value>
      <webElementGuid>426a402d-4e3a-415f-a8dd-51bf7c638813</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='113']</value>
      <webElementGuid>f08b1327-5fd5-4d97-bb38-e7846ae671f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[3]/div/div/form/div/div/div/div[2]/div/section[3]/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>f9f6e337-d2b5-4330-971b-227482a373ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/div/div/div/div[2]/input</value>
      <webElementGuid>3b37b1e3-0333-4d6e-8905-cc41524db1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>7a5f65bb-59f5-48a3-b80c-a1c6d2dd0674</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
