<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Annual Growth_client.salary.growth</name>
   <tag></tag>
   <elementGuidId>27cfb621-0847-4434-a6b1-6f3cbfebe483</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;client.salary.growth&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='client.salary.growth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5bee33a1-363e-4f35-a34e-3166884918e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>83a0dbd4-1e48-4f19-8122-277c345b568d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>client.salary.growth</value>
      <webElementGuid>1021d9c8-af89-4bbf-97b4-5cc86a8ba601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2fce485c-2e72-4a73-ba3a-8d06388fcb81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>50875c88-7de1-46ed-a706-5f750f569296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\$?[0-9]*,?[0-9]*\.?[0-9]*%?</value>
      <webElementGuid>06e0076c-81ca-40ed-af4d-fd79a4ebf266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>695c8fce-f3bb-4fce-8118-d5c2122a4c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3%</value>
      <webElementGuid>c65f994e-6b45-4db0-bbdb-fc3a4a452c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>c20ae706-1a59-4c18-8613-a81ec00b2fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[2]/div[@class=&quot;Body__Root-sc-jff9vc-0 BegZu&quot;]/div[@class=&quot;Body__Container-sc-jff9vc-1 dVTuVJ&quot;]/div[@class=&quot;InfoContent__Wrapper-sc-6smxw-0 cpEFfe&quot;]/form[1]/div[@class=&quot;mb-0 form-group row&quot;]/div[@class=&quot;pr-2 col&quot;]/div[@class=&quot;InfoContent__LeftPanel-sc-6smxw-1 hucjNN card&quot;]/div[@class=&quot;card-body&quot;]/div[1]/section[4]/div[@class=&quot;LayoutHelpers__InfoFieldGroup-sc-7ke78-5 bvUyZh&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;text-nowrap row&quot;]/div[@class=&quot;col-md-3 col-sm-3&quot;]/div[1]/div[@class=&quot;NumberField__Wrapper-sc-1rl9wva-0 hPJqcX&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>e5f5e5d3-a703-4d4e-b49e-2f1ca9aa56a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='client.salary.growth']</value>
      <webElementGuid>761d9f10-2e27-458a-aca3-6a05b6b278ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[3]/div/div/form/div/div/div/div[2]/div/section[4]/div/div/div/div[4]/div/div/input</value>
      <webElementGuid>00991b3c-35f4-4a18-8008-96abbced4879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>4c5d4904-782f-4f92-9c41-b6bf1214facc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'client.salary.growth' and @type = 'text']</value>
      <webElementGuid>20208262-cd19-46d9-a8c0-5dbbf69dc61c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
