<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login</name>
   <tag></tag>
   <elementGuidId>0d7dcfae-944e-4a62-aeb8-1f51d0bd0f02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ladda-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login-form']/div[3]/div[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6295ecc5-79ab-454b-8d64-a42839a974cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ladda-label</value>
      <webElementGuid>88c22754-d43f-4548-9016-1c81c344952c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>d6470952-10bc-45ec-a480-de72e462f750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-form&quot;)/div[@class=&quot;form-group row&quot;]/div[@class=&quot;input-wrapper col-sm-8&quot;]/button[@class=&quot;Button__DefaultButton-sc-ftu7s5-0 LaddaButton__StyledButton-sc-14zz3uc-0 Nbwot gkxRZX btn btn-primary ladda-button&quot;]/span[@class=&quot;ladda-label&quot;]</value>
      <webElementGuid>cc0b29ce-e4a3-42a8-95a8-9667631267c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div[3]/div[2]/button/span</value>
      <webElementGuid>7a48e640-2159-4ba2-a0b0-64cdfc83348f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password:'])[1]/following::span[1]</value>
      <webElementGuid>62a2f3dd-76d0-445d-88e0-815b19031bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address:'])[1]/following::span[1]</value>
      <webElementGuid>484f6ac0-e844-42af-ad1e-8c8834a97c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create your account'])[1]/preceding::span[2]</value>
      <webElementGuid>27960bb7-4d6e-4be7-b814-5e72f4a60b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>5b321d6e-b4fa-4c99-9311-e6c5b984df1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>89a85466-d20c-4da4-b4a6-b31d87181db6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
