<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_sign up for trial_password</name>
   <tag></tag>
   <elementGuidId>1146f513-be64-4802-8aa2-bc7e2dfecd59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password_login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;loginPassword&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96d3eb09-ff77-4f12-bbcc-f75df8303c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6e461543-b639-4d4c-80c8-95154859aa04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>7f737af1-89b0-45ad-babe-23c8106b9175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password_login</value>
      <webElementGuid>1e261e83-ba2d-4fd7-ba5e-a96ed845f307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>cf3eafa5-d875-441c-b246-a435acd17efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-password validate[required]</value>
      <webElementGuid>c310a046-76d3-43b2-8df2-91f2634d9012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password_login&quot;)</value>
      <webElementGuid>471a3fae-9f77-4d76-bca4-b7ddea5daa5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password_login']</value>
      <webElementGuid>1843dad4-cf46-4a25-a4e3-adf0a59e6ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signin_form']/div/input[2]</value>
      <webElementGuid>80b7b738-830d-4c0b-9a4c-7e3da40a3bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>7d3f12be-26d2-435b-ad0e-2dcd66c0ddc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Password' and @id = 'password_login' and @name = 'password']</value>
      <webElementGuid>418df88d-03b6-446e-beea-5794bffb7455</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
