<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Before Retirement_rc-slider-handle</name>
   <tag></tag>
   <elementGuidId>337313f4-e329-4a2e-98a5-bd33e6ee04c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.rc-slider-handle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hypoReturns']/div/div/div/div[3]/div/div[4]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2bffae46-0f2e-4e43-adbb-ccf2105c3264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f9799291-f162-497f-a365-a2a5159d1206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-slider-handle</value>
      <webElementGuid>be0f94dc-d15d-4356-b092-977b82295438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>slider</value>
      <webElementGuid>d936157d-0f6d-41f2-bf56-9f31d8cb9cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>-2</value>
      <webElementGuid>e2e4735d-ea8c-4ba0-8e65-0dd40c8ce4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemax</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>d545b004-c952-4218-a505-b045a75ccdd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e4219c4b-0afe-4699-b12d-f423b0a756bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hypoReturns&quot;)/div[@class=&quot;HypoReturns__Top-sc-1ue7709-4 dspOdQ&quot;]/div[@class=&quot;market-returns&quot;]/div[@class=&quot;before&quot;]/div[@class=&quot;slider&quot;]/div[@class=&quot;rc-slider General__StyledSlider-sc-1hdl0qx-0 cOZflH&quot;]/div[4]/div[@class=&quot;rc-slider-handle&quot;]</value>
      <webElementGuid>bdc95a82-9a40-4dc8-9665-779eb8ab7a2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hypoReturns']/div/div/div/div[3]/div/div[4]/div</value>
      <webElementGuid>b1db59df-03dc-481f-9bb4-d3b1b09ba741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[4]/div</value>
      <webElementGuid>18dd9e52-4263-4ada-ac94-ed0941ee8bf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
