<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Info</name>
   <tag></tag>
   <elementGuidId>290f8e91-fad2-4dbb-9a4e-da47ab237103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.StepLink__StyledLink-sc-1iedwva-0.eZWMlC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1cf0a256-34bd-433d-b200-3e5a30490d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Update information</value>
      <webElementGuid>13153ea7-9e48-4c4a-b0d2-cc90e4c77c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StepLink__StyledLink-sc-1iedwva-0 eZWMlC</value>
      <webElementGuid>c92698b0-78db-4b5d-96bd-7ac38f5ead04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/planning/info/913bae97eaf8fba686f0d844e6eb7189</value>
      <webElementGuid>459a3493-4dfd-4549-a023-affa144795bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Info</value>
      <webElementGuid>aafda6c8-bb57-4ef9-ac22-7ac72098a914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[2]/div[@class=&quot;Navigation__LeftNav-sc-ki3bt8-0 degmbO&quot;]/a[@class=&quot;StepLink__StyledLink-sc-1iedwva-0 eZWMlC&quot;]</value>
      <webElementGuid>28b665b9-a504-476e-bfba-01e034d2026c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]/a</value>
      <webElementGuid>1bf4d8a3-0709-4e77-b9c7-3b20ee4bd1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apr 03, 2023'])[1]/following::a[1]</value>
      <webElementGuid>30f52e5b-2541-4994-b5ab-5703eccc7e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Plan'])[1]/following::a[1]</value>
      <webElementGuid>280659df-e1f7-4e97-895e-e4fba1a4ab8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sources'])[1]/preceding::a[1]</value>
      <webElementGuid>674f57d8-6b30-4a92-86c4-1c61ee9cfa5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/planning/info/913bae97eaf8fba686f0d844e6eb7189')]</value>
      <webElementGuid>0d9731dd-fa1f-4bc1-9f54-29af68629925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a</value>
      <webElementGuid>fa451627-9517-4ee4-b74c-a2c699420841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Update information' and @href = '/planning/info/913bae97eaf8fba686f0d844e6eb7189' and (text() = 'Info' or . = 'Info')]</value>
      <webElementGuid>876f5cc5-78b5-4e52-b2ce-420da6a2abc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
