<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sources</name>
   <tag></tag>
   <elementGuidId>6bdeb61a-71ec-4d08-a8e4-1191521fbeff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d5852216-e04c-40cd-ac48-5990174a77c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Update financial sources</value>
      <webElementGuid>c8d614e4-c96c-4444-8554-bf134c7e557e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StepLink__StyledLink-sc-1iedwva-0 eZWMlC</value>
      <webElementGuid>16240279-06a3-490b-9753-22ddfcb6e7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/planning/sources/913bae97eaf8fba686f0d844e6eb7189</value>
      <webElementGuid>0145f49c-1b98-48a5-b17c-c97cb70346e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sources</value>
      <webElementGuid>ab039d13-152c-4012-bf83-ec85409f1d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[2]/div[@class=&quot;Navigation__LeftNav-sc-ki3bt8-0 degmbO&quot;]/a[@class=&quot;StepLink__StyledLink-sc-1iedwva-0 eZWMlC&quot;]</value>
      <webElementGuid>1c768702-f60b-40f7-9411-a3ccca2e3c28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]/a[2]</value>
      <webElementGuid>be67c826-ba65-4bef-805f-ff68c4f13cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info'])[1]/following::a[1]</value>
      <webElementGuid>7673bc79-8d2c-4bcd-bd95-ba2630351938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apr 06, 2023'])[1]/following::a[2]</value>
      <webElementGuid>81880cae-3ec2-494f-882e-24259b655d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expenses'])[1]/preceding::a[1]</value>
      <webElementGuid>d2a76ace-d882-4f47-88b3-8e74be90ad08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/planning/sources/913bae97eaf8fba686f0d844e6eb7189')]</value>
      <webElementGuid>ebaeafce-441f-489d-9144-2af5c9ac9557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[2]</value>
      <webElementGuid>728b9a3d-e9db-4b0e-8feb-14bbed4dec2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Update financial sources' and @href = '/planning/sources/913bae97eaf8fba686f0d844e6eb7189' and (text() = 'Sources' or . = 'Sources')]</value>
      <webElementGuid>0da22584-57c4-4ccf-b186-7ddab93e95a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
