<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tax 18</name>
   <tag></tag>
   <elementGuidId>fe65313b-6f96-4c9a-8bcb-218c14d45614</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.TaxSliderVariable__TriggerButton-sc-hizw2i-1.iEIPTU.btn.btn-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>84a9d842-4c9e-4f33-b08b-987cb3f60a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1cb7a927-c859-4f82-b16b-49e6c8923f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TaxSliderVariable__TriggerButton-sc-hizw2i-1 iEIPTU btn btn-link</value>
      <webElementGuid>38fb59e4-285d-4b3a-8f60-850ae3fe3f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tax 18%</value>
      <webElementGuid>0ae0d3a0-ea2f-496c-81b0-630189e172a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[2]/div[@class=&quot;Body__Root-sc-jff9vc-0 BegZu&quot;]/div[@class=&quot;Body__Container-sc-jff9vc-1 dVTuVJ&quot;]/div[@class=&quot;PlanContent__Container-sc-cm6oe-1 jBsyyo&quot;]/div[2]/div[@class=&quot;PlanContent__StatsCol-sc-cm6oe-4 gmFQlo&quot;]/div[@class=&quot;Stats__Container-sc-cs0c3e-4 faPrJm&quot;]/div[@class=&quot;details&quot;]/button[@class=&quot;TaxSliderVariable__TriggerButton-sc-hizw2i-1 iEIPTU btn btn-link&quot;]</value>
      <webElementGuid>0cbc2b9d-2cc7-47a4-8cb6-8c18e4553f16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>c3258eb5-3ac7-4240-95f8-2776e55a9ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[3]/div/div/div[2]/div/div/div[4]/button</value>
      <webElementGuid>21bf57b4-55e6-4c3c-828e-1cc096b87b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$3,275,814'])[1]/following::button[1]</value>
      <webElementGuid>c60b7d16-32ed-40ba-be0c-d5fa27bcee4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inflation 2.5%'])[1]/preceding::button[1]</value>
      <webElementGuid>f9006ae0-57b0-4a94-b45c-e269feb18bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Re-invest Surplus'])[1]/preceding::button[2]</value>
      <webElementGuid>af3a664d-5eb7-42a4-b197-36f3d5214f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tax 18%']/parent::*</value>
      <webElementGuid>961a4368-5661-4c5e-bea8-ed893cdd9bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>4a804aad-69ef-4f86-b63c-ea3ae70d6aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Tax 18%' or . = 'Tax 18%')]</value>
      <webElementGuid>a4b76f3e-e902-4471-ad51-a4710c0bad59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
