<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_concat(id(, , 0.8523213170892123, , )di_77fa8d</name>
   <tag></tag>
   <elementGuidId>8d86699d-3b23-4e9b-a69f-f1d9f43656a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.popover-body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='0.8523213170892123']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7b6af385-5ea5-4bd1-ba4c-c3a3d54f5e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popover-body</value>
      <webElementGuid>b02ca69c-7774-403b-83fd-51c0e57c1d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0.8523213170892123&quot;)/div[@class=&quot;popover-body&quot;]</value>
      <webElementGuid>d26d2213-0245-4f1a-88e9-1690e7fb2765</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0.8523213170892123']/div[2]</value>
      <webElementGuid>737a93c0-c691-408e-9067-c7d5d85fde1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '0.8523213170892123', '&quot;', ')/div[@class=', '&quot;', 'popover-body', '&quot;', ']')])[1]/following::div[7]</value>
      <webElementGuid>5cc37675-44a6-4bfc-8c7b-4b64b0aea2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need help?'])[1]/following::div[9]</value>
      <webElementGuid>7b445e2c-efc1-4702-9905-cc3fdc6dfad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]</value>
      <webElementGuid>c0380d58-ad89-48da-9d33-90d5ada3159a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
