<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Before Retirement_rc-slider-handle</name>
   <tag></tag>
   <elementGuidId>dc2968a8-cca1-446f-aafb-0286286fa1f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.rc-slider-handle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hypoReturns']/div/div/div/div[3]/div/div[4]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf5ac875-1f73-48af-867c-2d9039c30609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0301c233-d3ea-4a44-a921-16163670c5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-slider-handle</value>
      <webElementGuid>504fb53c-1fc8-4c5f-97fd-d8f3fc0f387d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>slider</value>
      <webElementGuid>6dc4ebcb-26f4-43a7-8713-a480229f0f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>-2</value>
      <webElementGuid>ce41fa56-d9fc-422b-9156-168cbed21d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemax</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>5ada92ea-fd3a-476f-9e34-d9b77da21e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>304b639d-5339-4794-843b-0dc8e9a69ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hypoReturns&quot;)/div[@class=&quot;HypoReturns__Top-sc-1ue7709-4 dspOdQ&quot;]/div[@class=&quot;market-returns&quot;]/div[@class=&quot;before&quot;]/div[@class=&quot;slider&quot;]/div[@class=&quot;rc-slider General__StyledSlider-sc-1hdl0qx-0 cOZflH&quot;]/div[4]/div[@class=&quot;rc-slider-handle&quot;]</value>
      <webElementGuid>5da54116-c688-4107-b00f-4f8ccbdacfcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hypoReturns']/div/div/div/div[3]/div/div[4]/div</value>
      <webElementGuid>a5ebdb03-6238-4e86-840d-67f3bc9546da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[4]/div</value>
      <webElementGuid>3bdba18f-bae0-4ef9-865e-2bbdd8597bfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
