<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Variable Tax Timeframe_TaxSliderVaria_b7b09c</name>
   <tag></tag>
   <elementGuidId>1ea2d3a4-47aa-4efb-a14b-641359961270</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.TaxSliderVariable__StyledNumericInput-sc-hizw2i-4.eabSpG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='18%']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fcb820b-bf53-480d-ab45-d4ade68ba556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>747d00a0-17db-406d-a366-2a1e523d773a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TaxSliderVariable__StyledNumericInput-sc-hizw2i-4 eabSpG</value>
      <webElementGuid>8162d775-2d7e-41ce-98b3-bda0b21e05d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\$?[0-9]*,?[0-9]*\.?[0-9]*%?</value>
      <webElementGuid>74ee397e-95c1-4b57-9b8c-161039d4890e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c0b16ee7-48e7-4ec9-ab71-4334bb9e04b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>18%</value>
      <webElementGuid>3ee2ed35-359e-4502-933a-f92964d6e629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>c3edc815-c897-425c-a283-5ce08c5fdbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tax-popover&quot;)/div[@class=&quot;popover-body&quot;]/div[1]/div[@class=&quot;TaxSliderVariable__SliderWithTextBoxContainer-sc-hizw2i-2 esDOdV&quot;]/div[@class=&quot;TaxSliderVariable__InputWrapper-sc-hizw2i-3 ijjCrq&quot;]/input[@class=&quot;TaxSliderVariable__StyledNumericInput-sc-hizw2i-4 eabSpG&quot;]</value>
      <webElementGuid>fb099f05-6227-4cad-8dde-d6fabd174741</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='18%']</value>
      <webElementGuid>de3d137c-deef-4943-adfe-fb2c60cf2a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tax-popover']/div[2]/div/div[2]/div/input</value>
      <webElementGuid>04e3f435-2eb5-4a05-9be2-d57fa16f9232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>90aec9ce-38ea-44b6-a3de-179def26798c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>082713a9-bbf1-4198-98f2-99460140a045</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
