<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pathMarketReturn1</name>
   <tag></tag>
   <elementGuidId>7165ff5a-b201-43bf-b4df-13cfae1d8d8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;hypoReturns&quot;]/div[2]/div/div[2]/svg/g[2]/path[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>g.return-bars > path</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[name()='path'])[31]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>69fd98e4-467d-4fb2-901e-3ecd67550c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M68,112.5
                        L68,109.55
                        A2,2 1 0 1 70, 107.55
                        L92.48275862068965,107.55
                        A2,2 1 0 1 94.48275862068965,109.55
                        L94.48275862068965,112.5Z</value>
      <webElementGuid>341afe6d-03bb-4014-8fec-f489f31d9fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>returns-tooltip</value>
      <webElementGuid>5faa2d2a-8a20-4605-8f52-57dd0206db79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;hypoReturns&quot;]/div[2]/div/div[2]/svg/g[2]/path[1]</value>
      <webElementGuid>9ad25d6e-de16-4564-9e87-255808da6c17</webElementGuid>
   </webElementProperties>
</WebElementEntity>
