<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>7165ff5a-b201-43bf-b4df-13cfae1d8d8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;hypoReturns&quot;]/div[2]/div/div[2]/svg/g[2]/path[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[name()='path'])[31]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>g.return-bars > path</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>026270f8-830f-43af-aeef-89e95130d83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M68,112.5
                        L68,109.55
                        A2,2 1 0 1 70, 107.55
                        L92.48275862068965,107.55
                        A2,2 1 0 1 94.48275862068965,109.55
                        L94.48275862068965,112.5Z</value>
      <webElementGuid>07b06eff-be4c-428b-9a7c-08a76c70db60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>returns-tooltip</value>
      <webElementGuid>876b4744-21fc-4352-ac90-72e301f6f0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;hypoReturns&quot;]/div[2]/div/div[2]/svg/g[2]/path[1]</value>
      <webElementGuid>7ad40ab3-69a5-48b5-af41-db9c465e1ccd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
