<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-EditAsset</name>
   <tag></tag>
   <elementGuidId>68cc1fdd-565c-4d3e-8780-2f745765f9d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.fade.StyledModal-sc-1dghfg2-0.elHOPi.modal.show</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;assets-tabpane-assets&quot;]/table/tbody/tr/td[8]/div/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>618d5298-c152-49c5-b31e-c50914fdeaa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>2d584b5d-5798-4ef7-9828-66cc107233f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4cbb7a77-a744-455c-a164-38fdba7ff1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fade StyledModal-sc-1dghfg2-0 elHOPi modal show</value>
      <webElementGuid>8b02b88b-d629-4474-aef4-604bd5650b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1a402113-d063-4931-9628-5f2829bd1820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assets BALANCE: TAX STATUS:QualifiedACCOUNT TYPE:IRAASSET TYPE:Fixed Index AnnuityPRODUCT:Power Index Elite with Income FIADESCRIPTION:Describe at the account level rather than a specific security or investment.  Ex: John's IRA or John's Brokerage Account.ValueBALANCE:Cost Basis:RIDER:Option 1Option 2INCOME RIDER STRATEGY:Cap 5.25%Fixed 2.4%Retirement IncomeINCOME PAYOUT:7.35%Payout Factor for Single Life : 7.35%.WITHDRAWAL STARTS:AgeYear: 2043Withdrawal's Age: 65 / Year: 2033Withdrawal will be 75PERIOD:Single LifeTAX EXEMPT:Withdrawals are NOT taxed.SAVE &amp; CONTINUE</value>
      <webElementGuid>0341ec0b-6c31-4087-b535-20c4d0a0a8e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ru-y-body-scrollbar modal-open&quot;]/div[@class=&quot;fade StyledModal-sc-1dghfg2-0 elHOPi modal show&quot;]</value>
      <webElementGuid>336d4bf6-13da-4cbf-b788-bc96da5844d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need help?'])[1]/following::div[6]</value>
      <webElementGuid>8f519466-7d84-4961-bceb-9a1cd966d68a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADD ASSET'])[1]/following::div[7]</value>
      <webElementGuid>28f54f28-3cf5-4405-9cb3-2e6eabb482ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]</value>
      <webElementGuid>eb156fba-ea85-4684-8b5f-03cc9f76680d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Assets BALANCE: TAX STATUS:QualifiedACCOUNT TYPE:IRAASSET TYPE:Fixed Index AnnuityPRODUCT:Power Index Elite with Income FIADESCRIPTION:Describe at the account level rather than a specific security or investment.  Ex: John&quot; , &quot;'&quot; , &quot;s IRA or John&quot; , &quot;'&quot; , &quot;s Brokerage Account.ValueBALANCE:Cost Basis:RIDER:Option 1Option 2INCOME RIDER STRATEGY:Cap 5.25%Fixed 2.4%Retirement IncomeINCOME PAYOUT:7.35%Payout Factor for Single Life : 7.35%.WITHDRAWAL STARTS:AgeYear: 2043Withdrawal&quot; , &quot;'&quot; , &quot;s Age: 65 / Year: 2033Withdrawal will be 75PERIOD:Single LifeTAX EXEMPT:Withdrawals are NOT taxed.SAVE &amp; CONTINUE&quot;) or . = concat(&quot;Assets BALANCE: TAX STATUS:QualifiedACCOUNT TYPE:IRAASSET TYPE:Fixed Index AnnuityPRODUCT:Power Index Elite with Income FIADESCRIPTION:Describe at the account level rather than a specific security or investment.  Ex: John&quot; , &quot;'&quot; , &quot;s IRA or John&quot; , &quot;'&quot; , &quot;s Brokerage Account.ValueBALANCE:Cost Basis:RIDER:Option 1Option 2INCOME RIDER STRATEGY:Cap 5.25%Fixed 2.4%Retirement IncomeINCOME PAYOUT:7.35%Payout Factor for Single Life : 7.35%.WITHDRAWAL STARTS:AgeYear: 2043Withdrawal&quot; , &quot;'&quot; , &quot;s Age: 65 / Year: 2033Withdrawal will be 75PERIOD:Single LifeTAX EXEMPT:Withdrawals are NOT taxed.SAVE &amp; CONTINUE&quot;))]</value>
      <webElementGuid>b9cd6eae-91d3-4c7f-86a1-78d3019261d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
