<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_4,000,000_AssetsList__EditButton-sc-_f3a0af</name>
   <tag></tag>
   <elementGuidId>cb235589-cf9c-4e2a-9aee-8b3365a4b3fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.AssetsList__EditButton-sc-1hp6jwl-2.dErZNF.btn-secondary.btn.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;assets-tabpane-assets&quot;]/table/tbody/tr/td[8]/div/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c3d33948-3faa-4eb4-9293-9f772c297067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>cd495d19-9d40-4b4d-90e7-600582a1525e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f6c5e847-fd82-429a-a51b-981324c900c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AssetsList__EditButton-sc-1hp6jwl-2 dErZNF btn-secondary btn btn-primary</value>
      <webElementGuid>42b85f60-6d51-4939-9630-6ec7631a1377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assets-tabpane-assets&quot;)/table[@class=&quot;table&quot;]/tbody[1]/tr[1]/td[8]/div[@class=&quot;AssetsList__RightButtons-sc-1hp6jwl-1 hmKZxL&quot;]/button[@class=&quot;AssetsList__EditButton-sc-1hp6jwl-2 dErZNF btn-secondary btn btn-primary&quot;]</value>
      <webElementGuid>0097ad68-206e-4c6c-afc7-aa2f15f62ffa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>fc50871f-eb5e-406f-bbd6-93a0858106a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='assets-tabpane-assets']/table/tbody/tr/td[8]/div/button</value>
      <webElementGuid>42b45bdf-9308-482d-a504-e2d95d0c5bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$4,000,000'])[1]/following::button[1]</value>
      <webElementGuid>24e64f52-69b0-4b0d-b7c9-df89f5107b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Withdrawal'])[1]/following::button[1]</value>
      <webElementGuid>dba78374-2cdd-41bf-99b0-2d32c7dcba36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$4,000,000'])[2]/preceding::button[2]</value>
      <webElementGuid>ae7aad92-34a6-4d98-afd2-c552c936bb00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADD ASSET'])[1]/preceding::button[2]</value>
      <webElementGuid>cbfb6227-234c-4eac-b832-59d18ad4f172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/button</value>
      <webElementGuid>322e2f46-451e-4128-9346-2da6fab715ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Edit' and @type = 'button']</value>
      <webElementGuid>b1f373f8-bfd8-4e5b-bc78-3df37f79f898</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
