<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Age_widthdrawStopTypeAge</name>
   <tag></tag>
   <elementGuidId>d9388b26-37fc-473c-b4c2-5176e446a731</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;widthdrawStopTypeAge&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='widthdrawStopTypeAge']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9867ba8-487c-439c-be10-6f5e57c3c7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ddb5afae-97e6-41a8-b2ef-8d128bc2e45f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>widthdrawStopTypeAge</value>
      <webElementGuid>91b66cff-a618-42bb-a08f-7fec7e5dc8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>55</value>
      <webElementGuid>25acddc1-e5ee-47a4-bdc6-f72770f938f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>edc14eff-3978-4118-a50c-1374fcff3516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\$?[0-9]*,?[0-9]*\.?[0-9]*%?</value>
      <webElementGuid>807fa33d-ccc0-42bb-bb6a-c51c3f3b9f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3972934a-a221-4ae3-a01c-66d8dcf0d87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>52621011-8b81-4735-966e-a38431e24e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>b0a2cd8e-156e-4b09-9054-3bb75300fbf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ru-y-body-scrollbar modal-open&quot;]/div[@class=&quot;fade StyledModal-sc-1dghfg2-0 elHOPi modal show&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/form[1]/div[1]/div[7]/div[9]/div[@class=&quot;collapse show&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;collapse show&quot;]/div[@class=&quot;LayoutHelpers__FlexRow-sc-18kklqx-0 irfXMQ&quot;]/div[1]/div[@class=&quot;NumberField__Wrapper-sc-987kzs-0 bDpQox&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>26ebd111-71f2-4d28-8a9e-51cf90540361</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='widthdrawStopTypeAge']</value>
      <webElementGuid>cd3e1adc-5e12-4944-a272-be65624ab3d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>ef23109b-b6cb-4e4e-838b-9981ca5a1c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'widthdrawStopTypeAge' and @type = 'text']</value>
      <webElementGuid>4fe93441-3c28-4794-be78-89cac1eef628</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
