<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input-WithdrawalStartAge</name>
   <tag></tag>
   <elementGuidId>f5e84910-2af9-49d4-9780-df17045f988f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;widthdrawStartTypeAge&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='widthdrawStartTypeAge'])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[@class=&quot;ru-y-body-scrollbar modal-open&quot;]/div[@class=&quot;fade StyledModal-sc-1dghfg2-0 elHOPi modal show&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/form[1]/div[1]/div[7]/div[8]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;collapse show&quot;]/div[@class=&quot;LayoutHelpers__FlexRow-sc-18kklqx-0 irfXMQ&quot;]/div[1]/div[@class=&quot;NumberField__Wrapper-sc-987kzs-0 bDpQox&quot;]/input[@class=&quot;form-control&quot;][count(. | //*[@name = 'widthdrawStartTypeAge' and @type = 'text']) = count(//*[@name = 'widthdrawStartTypeAge' and @type = 'text'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdbf6d26-b6de-4f9f-8e00-069a05970efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c9cfe080-9549-4ca7-905d-e6ca2df2e7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>widthdrawStartTypeAge</value>
      <webElementGuid>e5cedfb3-3b8b-4485-8d68-d39a17b2fd66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>c127db11-ac52-4593-bc4e-a1718adf0962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>ce266848-acf5-4070-ab44-2d0cf48082c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\$?[0-9]*,?[0-9]*\.?[0-9]*%?</value>
      <webElementGuid>fc67184b-9e69-4a17-97c3-4d56df804744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>49bf7fe6-10e2-4760-80bb-c4d52e3c2366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>3270dc6c-c657-4025-938b-721ec2c017a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>5ff62939-8016-45a7-8986-1779d83a986b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ru-y-body-scrollbar modal-open&quot;]/div[@class=&quot;fade StyledModal-sc-1dghfg2-0 elHOPi modal show&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/form[1]/div[1]/div[7]/div[8]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;collapse show&quot;]/div[@class=&quot;LayoutHelpers__FlexRow-sc-18kklqx-0 irfXMQ&quot;]/div[1]/div[@class=&quot;NumberField__Wrapper-sc-987kzs-0 bDpQox&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>f1d503aa-0a75-49e5-8809-6d932d1b6221</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='widthdrawStartTypeAge']</value>
      <webElementGuid>987dc642-e4c0-4b86-b6af-f87b6a3ad844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>fefb6150-2ae9-4647-9e81-a402feb0c857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'widthdrawStartTypeAge' and @type = 'text']</value>
      <webElementGuid>ca4c0807-09d3-4e5d-878d-fdf4e55e3765</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
