<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>planPage-sideNavigation</name>
   <tag></tag>
   <elementGuidId>8a410b91-e7dc-42e8-bc3b-3f4394103f34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[2]/div[2]/a[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
      <webElementGuid>4e80adeb-353b-4251-97cd-abcdd75eb823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>2ed4f7af-1cdd-4a0f-9715-c19f7b9b5878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>52004607-39f8-4520-bde4-f111dd1eeb20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>39</value>
      <webElementGuid>f9b50896-7bd0-47fa-9f22-6eb6d3464013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>f0aea683-9db9-4578-9a30-3c430c36facb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rx</name>
      <type>Main</type>
      <value>1.5</value>
      <webElementGuid>eb3641b1-c268-4112-88a5-9404d7281e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[2]/div[@class=&quot;Navigation__LeftNav-sc-1jg49zq-0 kclztT&quot;]/a[@class=&quot;StepLink__StyledLink-sc-1k2c664-0 dNIKQf&quot;]/svg[1]/g[1]/rect[2]</value>
      <webElementGuid>8aa07296-0564-4128-91df-e3613c85822b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
