<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sources</name>
   <tag></tag>
   <elementGuidId>093473ec-cdfd-4b98-8fc5-7ab819234c28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>320f1e3a-d7dd-47c3-8b79-d4075a769470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Update financial sources</value>
      <webElementGuid>c91781b4-f76f-40e9-a42c-81bf5a939d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StepLink__StyledLink-sc-1k2c664-0 dNIKQf</value>
      <webElementGuid>0d22c276-0fc0-4ebe-b59d-adae2eee6cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/planning/sources/23482e7a02efe66ea67896fd97fbf81e</value>
      <webElementGuid>0c1de744-7324-42f1-b0f7-3df04b865c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sources</value>
      <webElementGuid>21bb8ef2-bfd1-4a99-9661-e25b28fe05bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[2]/div[@class=&quot;Navigation__LeftNav-sc-1jg49zq-0 kclztT&quot;]/a[@class=&quot;StepLink__StyledLink-sc-1k2c664-0 dNIKQf&quot;]</value>
      <webElementGuid>dbb1b544-ad1b-46c6-997b-f969158e92ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]/a[2]</value>
      <webElementGuid>9e7be30f-155f-4c69-8d8e-ffa8efd549ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info'])[1]/following::a[1]</value>
      <webElementGuid>60f9f59d-d934-4fd8-9055-fdb801b1c427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mar 27, 2023'])[2]/following::a[2]</value>
      <webElementGuid>286d0fac-a5f5-40be-a87d-7ec2ec44d45f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expenses'])[1]/preceding::a[1]</value>
      <webElementGuid>f49250b0-284a-4333-8c07-ac60a62ee4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/planning/sources/23482e7a02efe66ea67896fd97fbf81e')]</value>
      <webElementGuid>45f5c6d5-8445-466d-94c8-4025cce0bc87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[2]</value>
      <webElementGuid>d9c22f2b-70af-46a1-a5b4-39b625183c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Update financial sources' and @href = '/planning/sources/23482e7a02efe66ea67896fd97fbf81e' and (text() = 'Sources' or . = 'Sources')]</value>
      <webElementGuid>372bb635-a592-4963-9865-32fbcfafad7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
