<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Test3</name>
   <tag></tag>
   <elementGuidId>71a1b282-5a7b-4bf3-b485-bb9c6e84f6f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[2]/div/div/div[4]/div[3]/div[3]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>edfd5279-898a-419a-a411-b47aaddbe727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/planning/plan/7fc8e0a72aa375904303aa5563cd7421</value>
      <webElementGuid>f0829375-eead-4ae7-91ac-207a06356dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Go to Plan step</value>
      <webElementGuid>f94cf98e-8a50-41ff-900d-9072f1ed6db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>components__UnderlineLink-sc-f99mkp-18 dnwPCM underline-link</value>
      <webElementGuid>58b8b36e-3a74-4965-93b2-c014ad3a2210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test3</value>
      <webElementGuid>201385d8-8ae5-4cc3-a2bb-ebf62f4ae062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;Body__Root-sc-pdu5og-0 gNVTUf&quot;]/div[@class=&quot;Body__Container-sc-pdu5og-1 irbQMo&quot;]/div[@class=&quot;Clients__Page-sc-18hpakg-0 eTATCf&quot;]/div[@class=&quot;components__TBODY-sc-f99mkp-2 ClientPlans__TBODY-sc-v3q02y-0 kxJMFe jDmizd ru-y-scrollbar&quot;]/div[@class=&quot;components__TR-sc-f99mkp-3 iwKevw client-case client row&quot;]/div[@class=&quot;components__TD-sc-f99mkp-4 YRsyQ col-sm-6&quot;]/div[@class=&quot;draft row&quot;]/div[@class=&quot;col-6&quot;]/a[@class=&quot;components__UnderlineLink-sc-f99mkp-18 dnwPCM underline-link&quot;]</value>
      <webElementGuid>c757aef1-1670-4f6f-856b-5945e7298e87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/div/div[4]/div[3]/div[3]/div/div/a</value>
      <webElementGuid>2c26067a-3992-4f97-9ee0-0f59d6fd6a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Test3')]</value>
      <webElementGuid>1b1f0514-5fde-48cb-860c-2b4def33d6b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plan3'])[1]/following::a[1]</value>
      <webElementGuid>4dfee0a7-92ce-4d1b-8219-26a8e4cc17cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contribution Test'])[1]/following::a[1]</value>
      <webElementGuid>35cb7ecf-1929-432e-b3ab-79b0057039b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mar 28, 2023'])[3]/preceding::a[1]</value>
      <webElementGuid>0dd07ca5-2040-40e7-9e03-4f0877af4ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plan'])[1]/preceding::a[1]</value>
      <webElementGuid>994a4c4c-4669-433f-97a9-1dc227f479a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test3']/parent::*</value>
      <webElementGuid>bed99013-1a5e-4e9a-8f18-0c579ce4dd03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/planning/plan/7fc8e0a72aa375904303aa5563cd7421')]</value>
      <webElementGuid>62117daf-7b07-48cb-884f-635b78cbd228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/a</value>
      <webElementGuid>1090b079-3b3b-4074-beb4-5f220d8fd829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/planning/plan/7fc8e0a72aa375904303aa5563cd7421' and @title = 'Go to Plan step' and (text() = 'Test3' or . = 'Test3')]</value>
      <webElementGuid>3a870c78-5f89-4c74-8387-31ae3cd987fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
