<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Test1</name>
   <tag></tag>
   <elementGuidId>53ddd5ac-1cdf-41c9-b21b-b7964611ce35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;wrapper&quot;]/div[2]/div[1]/div/div[4]/div[4]/div[3]/div/div[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f740b9bd-304b-40b9-9144-f28106ee532b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/planning/plan/23482e7a02efe66ea67896fd97fbf81e</value>
      <webElementGuid>f8929429-5429-4f0a-8bac-73525b1e3162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Go to Plan step</value>
      <webElementGuid>6b11da15-cd01-475d-8673-2fbaae3d895c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>components__UnderlineLink-sc-f99mkp-18 dnwPCM underline-link</value>
      <webElementGuid>95d2d514-27e6-4e0c-a84b-c52ac64a3965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test1</value>
      <webElementGuid>91cf320a-ad77-4d9e-9dea-64c2157e1c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;Body__Root-sc-pdu5og-0 gNVTUf&quot;]/div[@class=&quot;Body__Container-sc-pdu5og-1 irbQMo&quot;]/div[@class=&quot;Clients__Page-sc-18hpakg-0 eTATCf&quot;]/div[@class=&quot;components__TBODY-sc-f99mkp-2 ClientPlans__TBODY-sc-v3q02y-0 kxJMFe jDmizd ru-y-scrollbar&quot;]/div[@class=&quot;components__TR-sc-f99mkp-3 iwKevw client-case client row&quot;]/div[@class=&quot;components__TD-sc-f99mkp-4 YRsyQ col-sm-6&quot;]/div[@class=&quot;draft row&quot;]/div[@class=&quot;col-6&quot;]/a[@class=&quot;components__UnderlineLink-sc-f99mkp-18 dnwPCM underline-link&quot;]</value>
      <webElementGuid>86eb5299-7938-4757-b50c-527dc6af8eff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/div/div[4]/div[4]/div[3]/div/div/a</value>
      <webElementGuid>8b833bfe-f93b-4f35-b95f-27df4cce6278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Test1')]</value>
      <webElementGuid>97d5b137-6b97-450d-8927-ec53bcca54e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test1'])[1]/following::a[1]</value>
      <webElementGuid>b0b2f8a3-5b77-4e39-962b-6b4ebc953556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Withdrawal Test'])[1]/following::a[1]</value>
      <webElementGuid>91076877-7fbb-44b9-9823-d7c93b876aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mar 27, 2023'])[1]/preceding::a[1]</value>
      <webElementGuid>14a834d7-fd9a-4cfe-8f8f-003c8305e74e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plan'])[6]/preceding::a[1]</value>
      <webElementGuid>7866c611-2f99-44ed-a807-9f32258fe7be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/planning/plan/23482e7a02efe66ea67896fd97fbf81e')]</value>
      <webElementGuid>94c42d66-6a72-4a1d-b8dd-c8e234092769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/a</value>
      <webElementGuid>b09b647d-b6eb-49f5-8fd8-1471fd30669e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/planning/plan/23482e7a02efe66ea67896fd97fbf81e' and @title = 'Go to Plan step' and (text() = 'Test1' or . = 'Test1')]</value>
      <webElementGuid>b3f48317-5d1f-4693-853e-2a7c22461eb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
