<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign In_1</name>
   <tag></tag>
   <elementGuidId>3e3b7459-7952-407c-912f-b642c4199600</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signInBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='signInBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0bb4a23c-ec14-444a-8f35-f1f18611b07f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn white tiny no-hover</value>
      <webElementGuid>f5e336d5-73d0-485c-a3a8-d9699aeafbc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signInBtn</value>
      <webElementGuid>589b549b-9338-48a1-8ad5-89414af2c88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f4317235-36a6-4e8b-b643-f42cb21428fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>321f9563-d96e-4f46-a154-93bc7ccec2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signInBtn&quot;)</value>
      <webElementGuid>feb3fa8e-c686-49f2-ae93-da484d04291a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='signInBtn']</value>
      <webElementGuid>7d58df59-0304-47b1-a8c0-dd5d99e828c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/div[3]/button[2]</value>
      <webElementGuid>c4a906e8-31c9-4b24-bb14-4cd54383d301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>d13ea7b7-bcd9-4bb0-8c59-7e5b3c19e210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/following::button[2]</value>
      <webElementGuid>bab42219-e53b-45c7-814c-d581ed55a9e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[3]/preceding::button[1]</value>
      <webElementGuid>3502af6e-09b1-4625-b6b0-e7220cc1aab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In Instead?'])[1]/preceding::button[1]</value>
      <webElementGuid>3e1daa4c-7390-4bc3-8424-85aa1aefeef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/button[2]</value>
      <webElementGuid>329e77ec-fedc-4144-b1d4-b51c39fea972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'signInBtn' and @type = 'submit' and (text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>e9151fa3-2b5b-4220-b304-67933f51886a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
