<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Monthly_css-bsr4gf-indicatorContainer</name>
   <tag></tag>
   <elementGuidId>85a4805d-b701-4f70-9b5d-efff6389c5fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly'])[1]/following::div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a63ae031-7ba2-473e-ac14-39b4be541162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-bsr4gf-indicatorContainer</value>
      <webElementGuid>6b8adf35-7c1b-4b36-81b3-633073b6b8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ac43d2fe-566c-48d1-87fb-ba70f3e3550a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ru-y-body-scrollbar modal-open&quot;]/div[@class=&quot;fade StyledModal-sc-91ps9d-0 fALiTF modal show&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/form[1]/div[1]/div[8]/div[5]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;css-1d4ytge-container&quot;]/div[@class=&quot;css-8jadhh-control&quot;]/div[@class=&quot;css-1wy0on6&quot;]/div[@class=&quot;css-bsr4gf-indicatorContainer&quot;]</value>
      <webElementGuid>9e72a4ab-1903-48b3-997c-ab889086e014</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monthly'])[1]/following::div[2]</value>
      <webElementGuid>3222053f-c788-4c94-b56d-cd6a6e035ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EMPLOYEE'])[1]/following::div[8]</value>
      <webElementGuid>129590a7-fa40-4665-9529-784d5db4bedf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None'])[1]/preceding::div[2]</value>
      <webElementGuid>d0f27b88-eefd-4eac-9d92-c2454557d947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum Allowable'])[1]/preceding::div[3]</value>
      <webElementGuid>3813e228-8f6a-4be4-afc8-70dd4b87ca05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div/div/div[2]/div</value>
      <webElementGuid>8dcfd6f2-10f1-4088-82aa-9f0ae9d9348e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
