<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sources</name>
   <tag></tag>
   <elementGuidId>f2d52816-503f-4ca7-bcfa-34e86150f418</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e28db740-4ed5-46f5-bff3-11827ed54bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Update financial sources</value>
      <webElementGuid>d003a8f6-1e3f-464e-891e-60ea847eeec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StepLink__StyledLink-sc-1iedwva-0 eZWMlC</value>
      <webElementGuid>22f9eb2a-6dd5-41ae-a2ee-2c148907e531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/planning/sources/913bae97eaf8fba686f0d844e6eb7189</value>
      <webElementGuid>5265d34a-3b38-49ed-8f99-1046cf70135b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sources</value>
      <webElementGuid>84aee394-c966-4465-bb4f-bcf34e6ea13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[2]/div[@class=&quot;Navigation__LeftNav-sc-ki3bt8-0 degmbO&quot;]/a[@class=&quot;StepLink__StyledLink-sc-1iedwva-0 eZWMlC&quot;]</value>
      <webElementGuid>7a4e1dd1-e592-40f8-b293-4ab98b4dae4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]/a[2]</value>
      <webElementGuid>9247da6b-2f6e-43c3-ba7b-6c6aa7b44567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info'])[1]/following::a[1]</value>
      <webElementGuid>d11a7063-6044-488f-ab1c-82dcbb58771a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apr 13, 2023'])[1]/following::a[2]</value>
      <webElementGuid>f6c7bdcb-cdca-4835-9e0d-9a12d0b34940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expenses'])[1]/preceding::a[1]</value>
      <webElementGuid>6ee4272f-1bbb-4176-a124-d1677f787dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/planning/sources/913bae97eaf8fba686f0d844e6eb7189')]</value>
      <webElementGuid>14352b47-1e3d-43c6-b738-3afbe68c59df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[2]</value>
      <webElementGuid>e4242a35-a7d9-4339-bf5d-2a04f1614427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Update financial sources' and @href = '/planning/sources/913bae97eaf8fba686f0d844e6eb7189' and (text() = 'Sources' or . = 'Sources')]</value>
      <webElementGuid>65306187-0bdf-4b60-85c0-04d6cc7f5eb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
