<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Show all clients</name>
   <tag></tag>
   <elementGuidId>ad2f8e48-1472-493b-8621-529cfe0eb003</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Button__DefaultButton-sc-ftu7s5-0.Nbwot.toggle-show-clients.btn.btn-secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7051ffe8-aa9c-4671-9e75-5b06ec9abe6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Show or hide clients</value>
      <webElementGuid>cc3bad1b-76cb-40a4-b19d-64c0ed9470f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ffd27953-41a5-4f62-9ba0-de5cddffab96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Button__DefaultButton-sc-ftu7s5-0 Nbwot toggle-show-clients btn btn-secondary</value>
      <webElementGuid>70f92e51-528d-4508-9ae3-501f9439caea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Show all clients</value>
      <webElementGuid>5bb7a722-a42e-4b1e-a9c3-91ee9e8e6dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;Body__Root-sc-1wxtz6s-0 khZfNO&quot;]/div[@class=&quot;Body__Container-sc-1wxtz6s-1 czRcOV&quot;]/div[@class=&quot;Clients__Page-sc-lzcexa-0 fXPcsO&quot;]/div[@class=&quot;Clients__ControlRibbon-sc-lzcexa-4 gUEIjL row&quot;]/div[@class=&quot;Clients__ControlGroup-sc-lzcexa-5 jMnmeO col-8&quot;]/button[@class=&quot;Button__DefaultButton-sc-ftu7s5-0 Nbwot toggle-show-clients btn btn-secondary&quot;]</value>
      <webElementGuid>4bc02073-6bf3-411d-aab3-078db15d0921</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>0ceb89db-2328-44cb-ae55-d4dbbdfe01e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/div/div[2]/div[2]/button[2]</value>
      <webElementGuid>615b43dc-6003-4e00-9db0-735d4ac51f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New client'])[1]/following::button[1]</value>
      <webElementGuid>7a65cf46-aec1-4100-a3c8-1a9c310084ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Plans'])[2]/following::button[2]</value>
      <webElementGuid>a1df01ca-4b42-4670-b555-422a0e3102f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Need help?'])[1]/preceding::button[1]</value>
      <webElementGuid>960669a9-1171-4b3d-ba74-dc8e362c919d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Show']/parent::*</value>
      <webElementGuid>d793ffb0-1fda-47a6-9319-4cbff041189a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>e60c435b-5d98-4a3f-b721-6b0e17c2e030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Show or hide clients' and @type = 'button' and (text() = 'Show all clients' or . = 'Show all clients')]</value>
      <webElementGuid>e83b753b-8944-4c4b-a2e9-48e9bcbffadb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
