<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Employer_AssetsList__EditButton-sc-n_517339</name>
   <tag></tag>
   <elementGuidId>df1ac24a-3ad2-4536-8b15-235aa18c7ced</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.AssetsList__EditButton-sc-nh3q7p-2.fWAPFA.btn-secondary.btn.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6fe4f2c3-5aa3-4008-8461-b13c7d8b79cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>473f7ea4-e42a-42b0-9b8c-20be6db092e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f55a80cf-6b80-4cce-b17f-8d6c03f642c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AssetsList__EditButton-sc-nh3q7p-2 fWAPFA btn-secondary btn btn-primary</value>
      <webElementGuid>83e9dc98-75e6-4585-8b53-ec824334aae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assets-tabpane-assets&quot;)/table[@class=&quot;table&quot;]/tbody[1]/tr[1]/td[8]/div[@class=&quot;AssetsList__RightButtons-sc-nh3q7p-1 gzNxXO&quot;]/button[@class=&quot;AssetsList__EditButton-sc-nh3q7p-2 fWAPFA btn-secondary btn btn-primary&quot;]</value>
      <webElementGuid>a8276198-bd04-436f-a7e6-0a9787145c18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>ea9ac01b-f55d-4810-9b88-cc2243478289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='assets-tabpane-assets']/table/tbody/tr/td[8]/div/button</value>
      <webElementGuid>a56c942d-2316-4867-a005-2aead489f93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employer:'])[1]/following::button[1]</value>
      <webElementGuid>458b8116-31a4-4ce3-8a82-6379758f4e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$2,000,000'])[2]/preceding::button[2]</value>
      <webElementGuid>0f2afeb2-ceab-4ed3-8ed0-6c33c6e6efa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADD ASSET'])[1]/preceding::button[2]</value>
      <webElementGuid>7992c004-ef46-4186-a85c-9202efcd9936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/button</value>
      <webElementGuid>5a83e2e0-0f20-4553-a899-9658711fc21f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Edit' and @type = 'button']</value>
      <webElementGuid>c9591405-352e-45af-a4a2-bf4205592364</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
