<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__slider-input</name>
   <tag></tag>
   <elementGuidId>9d97e55c-745f-423a-b3f9-5797ac928c1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.slider-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='2.4%']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0561c1dc-4e96-4c39-ac61-8ff6a7b707ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider-input</value>
      <webElementGuid>f463bb1e-240c-49ff-9c88-5218d8e80167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>6c0701e0-98ca-49f8-8e5e-584bcf6dbf23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>25%</value>
      <webElementGuid>635c72fb-6f64-4655-9d37-423d5e6a4584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\$?[0-9]*,?[0-9]*\.?[0-9]*%?</value>
      <webElementGuid>f010395d-6a1f-4f2b-9d52-cabe43710f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>28ba9292-a2ce-456d-ac14-49d78b5b8f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2.4%</value>
      <webElementGuid>80bc6e2e-c4ab-4e02-a8b7-4e74dcdc3730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>4b9e7923-e0b9-485b-82a2-9eacd5d1d069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0.09773824296886979&quot;)/div[@class=&quot;popover-body&quot;]/div[@class=&quot;slider-input-container&quot;]/input[@class=&quot;slider-input&quot;]</value>
      <webElementGuid>36da3a7d-1602-45a6-9143-9feaaad91bb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='2.4%']</value>
      <webElementGuid>bae23c1c-0426-49fc-8a51-3b3b4f6e19f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='0.09773824296886979']/div[2]/div/input</value>
      <webElementGuid>d916fc6a-421c-466e-8afb-7ea0b680f61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>2d6d20f5-dd0b-49a2-9229-bcd9ad451ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>635139b3-72a5-42a1-be92-d5d78e7c71c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
